// Decompiled with JetBrains decompiler
// Type: CharacterEditor.EType
// Assembly: CharacterEditor, Version=1.4.1242.0, Culture=neutral, PublicKeyToken=null
// MVID: 31AEEDD2-5E67-4752-86A4-C61702D6EBC1
// Assembly location: O:\SteamLibrary\steamapps\common\RimWorld\Mods\CharacterEditor\v1.5\Assemblies\CharacterEditor.dll

namespace CharacterEditor;

internal enum EType
{
    ApparelTags,
    GraphicPaths,
    Bodies,
    CostItems,
    EditorUI,
    Factions,
    Inspirations,
    MainButton,
    TeleButton,
    MentalStates,
    ModsThingDef,
    ModsWeapons,
    ModsApparel,
    ModsHediffDef,
    ModsTraitDef,
    ModsHairDef,
    ModsBeardDef,
    ModsAbilityDef,
    OutfitTags,
    PawnKindAnimal,
    PawnKindHuman,
    PawnKindOther,
    PawnKindListed,
    Pawns,
    Search,
    Settings,
    StatCategoryApparel,
    StatCategoryOnEquip,
    StatCategoryWeapon,
    StatDefApparel,
    StatDefOnEquip,
    StatDefWeapon,
    StuffCategory,
    TechLevel,
    ThoughtMemory,
    ThoughtMemorySocial,
    ThoughtsAll,
    ThoughtSituational,
    ThoughtSituationalSocial,
    ThoughtUnsupported,
    Tradeability,
    UIContainers,
    WeaponTags,
    TradeTags,
    ExclusionTags,
    HairTags,
    BeardTags,
    GenePreset,
    ObjectPreset,
    TurretPreset,
    LifestagePreset,
    Bullet,
    ThingCategory,
    ThingCategoryDef,
    ApparelLayerDef,
    BodyPartGroupDef,
    WeaponType,
    QualityCategory,
    WeaponTraitDef,
    ResearchProjectDef,
    GasType,
    ExplosionSound,
    GunRelatedSound,
    GunShotSound,
    EffecterDef,
    DamageDef,
    Capturer
}